# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_post_name', models.CharField(max_length=30)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff_Management.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('working_address', models.CharField(max_length=100)),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('emile', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateTimeField()),
                ('Photo', models.ImageField(blank=True, upload_to='Staff/')),
                ('performance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Welder',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff_Management.Staff')),
                ('qualification', models.CharField(blank=True, choices=[('A', 'Senior Welding Technician'), ('B', 'Welding Technician'), ('C', 'Senior Welder'), ('D', 'Intermediate Welder'), ('E', 'Primary Welder')], max_length=1, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('prolongation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff_Management.DepartmentPost'),
        ),
    ]
