# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff_Management', '0001_initial'),
        ('WPS_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualWeldingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('sound', models.FloatField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='ActualWeldingData/')),
                ('prediction_of_tensile_properties', models.FloatField(blank=True, null=True)),
                ('prediction_of_fatigue_strength', models.FloatField(blank=True, null=True)),
                ('prediction_of_bending_strength', models.FloatField(blank=True, null=True)),
                ('pore', models.NullBooleanField()),
                ('slag', models.NullBooleanField()),
                ('prediction_of_frontal_melt_width', models.FloatField(blank=True, null=True)),
                ('prediction_of_back_melt_width', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskArrangementLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinates', models.FloatField(blank=True, null=True)),
                ('y_coordinates', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeldingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_sketch', models.ImageField(upload_to='WeldingProject/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeldingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_welding_time', models.DateTimeField(blank=True, null=True)),
                ('start_time_of_actual_welding', models.DateTimeField(blank=True, null=True)),
                ('duration_time', models.IntegerField(blank=True, null=True)),
                ('wps_deviation', models.CharField(blank=True, max_length=100, null=True)),
                ('corrective_measures', models.TextField(blank=True, null=True)),
                ('detection_result_of_tensile_properties', models.FloatField(blank=True, null=True)),
                ('detection_result_of_fatigue_strength', models.FloatField(blank=True, null=True)),
                ('detection_result_of_bending_strength', models.FloatField(blank=True, null=True)),
                ('detection_result_of_frontal_melted_width', models.FloatField(blank=True, null=True)),
                ('detection_result_of_back_melted_width', models.FloatField(blank=True, null=True)),
                ('detection_result_of_penetration_depths', models.CharField(max_length=10)),
                ('taskarrangementlocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.TaskArrangementLocation')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff_Management.Welder')),
                ('wps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WPS_Management.WPS')),
            ],
        ),
        migrations.AddField(
            model_name='taskarrangementlocation',
            name='weldingproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.WeldingProject'),
        ),
        migrations.AddField(
            model_name='actualweldingdata',
            name='welding_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.WeldingTask'),
        ),
    ]
