# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Material_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABaseMetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('groove_type', models.IntegerField(blank=True, null=True)),
                ('groove_parameter1', models.FloatField(blank=True, null=True)),
                ('groove_parameter2', models.FloatField(blank=True, null=True)),
                ('groove_parameter3', models.FloatField(blank=True, null=True)),
                ('thickness_type', models.IntegerField(blank=True, null=True)),
                ('groove_machine_method', models.CharField(blank=True, max_length=100, null=True)),
                ('basemetal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.BaseMetal')),
            ],
        ),
        migrations.CreateModel(
            name='BBaseMetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('groove_type', models.IntegerField(blank=True, null=True)),
                ('groove_parameter1', models.FloatField(blank=True, null=True)),
                ('groove_parameter2', models.FloatField(blank=True, null=True)),
                ('groove_parameter3', models.FloatField(blank=True, null=True)),
                ('thickness_type', models.IntegerField(blank=True, null=True)),
                ('groove_machine_method', models.CharField(blank=True, max_length=100, null=True)),
                ('basemetal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.BaseMetal')),
            ],
        ),
        migrations.CreateModel(
            name='WeldConditionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welding_sequence', models.IntegerField(blank=True, null=True)),
                ('layer', models.IntegerField(blank=True, null=True)),
                ('path', models.IntegerField(blank=True, null=True)),
                ('welding_method', models.CharField(blank=True, max_length=50, null=True)),
                ('current_polarity', models.CharField(blank=True, choices=[('N', 'DCEN'), ('P', 'DCEP')], max_length=1, null=True)),
                ('max_current', models.FloatField(blank=True, null=True)),
                ('min_current', models.FloatField(blank=True, null=True)),
                ('max_voltage', models.FloatField(blank=True, null=True)),
                ('min_voltage', models.FloatField(blank=True, null=True)),
                ('welding_speed', models.FloatField(blank=True, null=True)),
                ('tungsten_pole_diameter', models.FloatField(blank=True, null=True)),
                ('nozzle_diameter', models.FloatField(blank=True, null=True)),
                ('frontal_gas_flow', models.FloatField(blank=True, null=True)),
                ('back_gas_flow', models.FloatField(blank=True, null=True)),
                ('auxiliary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.Auxiliary')),
                ('protective_gas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.ProtectiveGas')),
                ('welding_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.WeldingMachine')),
                ('welding_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.WeldingMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='WeldingMaterialTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baking_temperature', models.IntegerField(blank=True, null=True)),
                ('preservationg_time', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('weldingmaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Management.WeldingMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='WPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_detecting', models.CharField(blank=True, max_length=100, null=True)),
                ('groove_clean_method', models.CharField(blank=True, max_length=100, null=True)),
                ('weld_root_clean_method', models.CharField(blank=True, max_length=100, null=True)),
                ('preheat_temperature', models.IntegerField(blank=True, null=True)),
                ('preheat_preservation_method', models.IntegerField(blank=True, null=True)),
                ('interlayer_temperature', models.IntegerField(blank=True, null=True)),
                ('PWHT', models.CharField(blank=True, max_length=100, null=True)),
                ('welder_qualification_demand', models.CharField(blank=True, choices=[('A', 'Senior Welding Technician'), ('B', 'Welding Technician'), ('C', 'Senior Welder'), ('D', 'Intermediate Welder'), ('E', 'Primary Welder')], max_length=1, null=True)),
                ('mark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalPropertiesOfWelds',
            fields=[
                ('mpwid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WPS_Management.WPS')),
                ('tensile_properties', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('bending_strength', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('impact_toughness', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('fatigue_strength', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('heat_resistant_crack', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('corrosion_resistance', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('hardness', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
                ('anti_lamellar_tearing', models.CharField(blank=True, choices=[('O', 'ordinary'), ('S', 'strong'), ('E', 'extremely strong')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeldArtwork',
            fields=[
                ('waid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WPS_Management.WPS')),
                ('joint_type', models.CharField(blank=True, choices=[('b', 'butt joint'), ('f', 'fillet joint')], max_length=1, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('relative_position', models.CharField(blank=True, choices=[('A', 'Top'), ('B', 'Middle'), ('C', 'bottom')], max_length=1, null=True)),
                ('top_layer_pass_type', models.CharField(blank=True, choices=[('A', '1-1'), ('B', '1-1,2-1'), ('C', '1-1,2-2'), ('D', '1-1,2-1,3-2'), ('E', '1-1,2-2,3-3'), ('F', '1-1,2-2,3-3,4-4'), ('G', '1-1,2-2,3-3,4-4,5-5'), ('H', '1-1,2-1,3-1'), ('I', '1-1,2-1,3-1,4-1'), ('J', '1-1,2-1,3-2,4-2'), ('K', 'None')], max_length=1, null=True)),
                ('bottom_layer_pass_type', models.CharField(blank=True, choices=[('A', '1-1'), ('B', '1-1,2-1'), ('C', '1-1,2-2'), ('D', '1-1,2-1,3-2'), ('E', '1-1,2-2,3-3'), ('F', '1-1,2-2,3-3,4-4'), ('G', '1-1,2-2,3-3,4-4,5-5'), ('H', '1-1,2-1,3-1'), ('I', '1-1,2-1,3-1,4-1'), ('J', '1-1,2-1,3-2,4-2'), ('K', 'None')], max_length=1, null=True)),
                ('A_base_metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WPS_Management.ABaseMetal')),
                ('B_base_metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WPS_Management.BBaseMetal')),
            ],
        ),
        migrations.AddField(
            model_name='weldconditionparameter',
            name='wps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WPS_Management.WPS'),
        ),
    ]
